# Generated by Django 2.2.6 on 2019-12-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendn', models.CharField(max_length=30)),
                ('tenkh', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('sdt', models.CharField(max_length=11)),
            ],
        ),
    ]
