# Generated by Django 2.2.6 on 2019-12-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khachhang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='id',
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='tendn',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
