# Generated by Django 2.2.6 on 2019-12-18 04:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khachhang', '0002_auto_20191218_1105'),
        ('phong', '0002_auto_20191218_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietBooking',
            fields=[
                ('mabooking', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ngaynhanphong', models.DateTimeField(default=datetime.datetime(2019, 12, 18, 4, 45, 49, 863859, tzinfo=utc))),
                ('ngaytratphong', models.DateTimeField(default=datetime.datetime(2019, 12, 18, 4, 45, 49, 863859, tzinfo=utc))),
                ('thanhtien', models.BigIntegerField(default=0)),
                ('sophong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.Phong')),
                ('tendn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khachhang.KhachHang')),
            ],
        ),
    ]
