# Generated by Django 2.2.6 on 2019-12-18 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chitietbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietbooking',
            name='ngaynhanphong',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 4, 47, 57, 233713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chitietbooking',
            name='ngaytratphong',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 4, 47, 57, 233713, tzinfo=utc)),
        ),
    ]
