# Generated by Django 2.2.6 on 2019-12-18 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chitietbooking', '0002_auto_20191218_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietbooking',
            name='ngaynhanphong',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chitietbooking',
            name='ngaytratphong',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
