# Generated by Django 2.2.6 on 2019-12-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='gia',
            field=models.BigIntegerField(default=0),
        ),
    ]
