# Generated by Django 2.2.6 on 2019-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0002_auto_20191218_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='phong',
            field=models.IntegerField(default=0, verbose_name={(0, 'Thường'), (1, 'Trung bình'), (2, 'Cao cấp')}),
        ),
    ]
