# Generated by Django 2.2.6 on 2019-12-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0003_phong_phong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='phong',
            field=models.IntegerField(choices=[(2, 'Cao cấp'), (1, 'Trung bình'), (0, 'Thường')], default=0),
        ),
    ]
