# Generated by Django 2.2.6 on 2019-12-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0004_auto_20191218_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phong',
            name='phong',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='tenloaiphong',
        ),
        migrations.AddField(
            model_name='phong',
            name='loaiphong',
            field=models.IntegerField(choices=[(1, 'Trung bình'), (2, 'Cao cấp'), (0, 'Thường')], default=0),
        ),
    ]
