# Generated by Django 2.2.6 on 2019-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0006_auto_20191218_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='loaiphong',
            field=models.IntegerField(choices=[(1, 'Phòng đơn'), (2, 'Phòng đôi'), (3, 'Phòng trẻ em'), (0, 'Phòng cao cấp Loại 1')], default=0),
        ),
    ]
