# Generated by Django 2.2.6 on 2019-12-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0008_auto_20191218_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='loaiphong',
            field=models.IntegerField(choices=[(2, 'Phòng đôi'), (1, 'Phòng đơn'), (0, 'Phòng cao cấp Loại 1'), (3, 'Phòng trẻ em')], default=0),
        ),
    ]
